version: '3.5'
services:
  peercoind:
    image: peerchemist/peercoind
    restart: always
    environment:
      - RPC_USER=USER
      - RPC_PASSWORD=PASS
    volumes:
      - type: bind
        source: /opt/electrum/peercoin/
        target: /data
    command:
      -nominting
      -rpcallowip=*
      -printtoconsole
  electrumx:
    image: peerchemist/electrumx
    environment:
      - DAEMON_URL=USER:PASS@peercoind
      - COIN=Peercoin
      - DB_DIRECTORY=/data
      - TCP_PORT=50001
      - SSL_PORT=50002
      - CACHE_MB=400
      - RPC_HOST=127.0.0.1
      - HOST=
      - RPC_PORT=58000
    volumes:
      - type: bind
        source: /opt/electrum/db/
        target: /data
    ports:
      - "50001:50001" # comment out to disable TCP port (plaintext)
      - "50002:50002"
      - "58000:58000"
    restart: always
    depends_on:
      - peercoind